config/routes.rb
Rails.application.routes.draw do
  match "/index" => "main#index", via: :get
  match "/about" => "main#about", via: :get
  match "/join" => "main#join", via: :get
  match "/need" => "main#need", via: :get
  match "/programme" => "main#programme", via: :get
  match "/newsletters" => "main#newsletters", via: :get
  match "/get_there" => "main#get_there", via: :get

  root 'main#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @title = "Home"
  end

  def about
    @title = "About Us"
  end

  def join
    @title = "How to Join"
  end

  def need
    @title = "What you need"
  end

  def programme
    @title = "2015 Programme"
  end

  def newsletters
    @title = "newsletters"
  end

  def get_there
    @title = "How to Get There"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return a title on a per-page basis

  def title
    base_title = "Cheam Croquet & Bowls Club"
    if @title.nil?
      base_title
    else
    "#{base_title} | #{@title}"
    end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("CCBC_Logo.jpg") %>
  <h1>Cheam Croquet & Bowls Club</h1>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Us", about_path %></li>
      <li><%= link_to "How to Join", join_path %></li>
      <li><%= link_to "What You Need", need_path %></li>
      <li><%= link_to "2015 Programme", programme_path %></li>
      <li><%= link_to "Finding Us", get_there_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <article id='main'>
    <%= render 'layouts/header' %>
    <%= yield %>
  </article>
</body>
</html>

app/views/main/about.html.erb
<section class="intro">
  <h1>About the Club</h1>
  <h2>History</h2>
  <p>
    The Club was founded in 2012 taking over a bowling green from a bowls club that had closed. The site is leased from Sutton Council.
  </p>
  <p>
    The Club is affiliated to the Croquet Association - www.croquet.org.uk - and the South East Croquet Federation – www.croquet.org.uk/secf/
  </p>
  <h2>Facilities</h2> 
  <p>
    The Club took over a high quality bowling green which the members now maintain. There is room for one full-sized croquet lawn with an additional area which can be used for bowls so that both games can be played at the same time. Generally however there are separate sessions for croquet and bowls and the two games co-exist comfortably together.
  </p>
  <p>
    There is a large clubhouse with tea and coffee making facilities and toilets. The Clubhouse can comfortably accommodate forty people for social events and meetings.
  </p>
  <p>
    The Club is open for playing croquet all year unless the lawn is frosted or very wet. Bowls is generally played between April and September.
  </p>
  <h2>Club sessions</h2>
  <p>
    There are Club sessions for Golf Croquet on Tuesday, Wednesday and Saturday mornings and Thursday and Sunday afternoons. There is one session for Association Croquet each Sunday morning and two sessions for Bowls on Monday and Wednesday afternoons between April,and September. 
  </p>
  <p>
    The morning sessions are from 10am – 1pm. In the summer afternoon sessions are from 2 – 5pm and in the winter from 1 - 4pm.
  </p>
  <p>
    During Club sessions members play with whichever other members are present. If you arrive at a Club session and there is no one else there it is a good opportunity to set the hoops out and do some practice. This sort of practice can be very valuable in improving your skills. 
  </p>
  <p>
    Play on the full lawn when you can as it is much better practice. The half lawns should normally only be used when there are more than 8 members at a session. 
  </p>
  <p>
    When there are not club sessions or club events, the lawn can be booked by members for games which they have arranged.
  </p>
  <h2>Coaching</h2>
    The Club now has 4 qualified Croquet coaches – Ian and Jean Cobbold for Golf Croquet and Neil Coote and Jon Criddle for Association Croquet. 
  </p>
  <p>
    Golf croquet coaching sessions are offered during the spring and summer and  members can ask any of the coaches for assistance at any time.
  </p>
  <p>
    Members who would like coaching for Bowls should contact John Davies.. 
  </p>
  <h2>Competitions and matches</h2>
    The Club organises a number of internal competitions which are a good introduction to competitive play. Some members play in external tournaments organised by the Croquet Association, South East Croquet Federation (SECF) or other clubs.
  </p>
  <p>
    The Club enters a team in the SECF’s Handicap Golf League and hopes to be able to enter a team in an Association League in 2015.
  </p>
  <p>
    The Club had a successful season in 2014 winning its first trophy in the Doubles Competition at the SECF’s Golf Teams Day and coming 4th in the SECF’s Golf Handicap League, out of 16 teams.
  </p>
  <h2>Social Events</h2>
  <p>
    The Club holds a number of social events including monthly tea and cakes afternoons during the summer, a BBQ, a Quiz Night and an Annual Dinner.
  </p>
</section>

app/views/main/get_there.html.erb
<section class="intro">
<h1>Where to find us and contact information</h1>
<p>
  To contact the Club e-mail 
  <a href="mailto:cheamcroquetbowlsclub@gmail.com">
    cheamcroquetbowlsclub@gmail.com</a>
  or phone 0208 642 0533.
</p>
<p>
  The Club is located in Cheam Recreation Ground, Tudor Close, Cheam, Sutton, Surrey SM3 8QS.  (This address should not be used for correspondence.)
</p>
<p>
  Directions: From the A2043 just north of Cheam Village turn into Tudor Close. At the end of the road go through gates to enter the free car park. The Club (marked Bowling Green on the map) is just inside the Recreation Ground opposite a children’s playground.
</p>
</section>

app/views/main/index.html.erb
<section class="intro">
  <h1>Cheam Croquet and Bowls Club</h1>
  <p>
    Welcome to the Cheam Croquet and Bowls Club's web site. You will find here the details 
    of how to contact and join us, together with some basic information about the Club.
  </p>
  <p>
    The Club is located in Cheam Recreation Ground, and has one full-sized croquet lawn within a bowling green. Currently we have 81 members, with 70 primarily playing Croquet and 11 primarily playing Bowls. </p>
  </p>
  <p>
    Members of the public are welcome to try playing croquet or bowls during our regular club sessions between April and September. The first 4 sessions are free after which you would be expected to join the Club – there is a waiting list for croquet membership – or to come as the guest of a member. 
  </p>
  <p>
    The Club runs a public coaching course for croquet each summer, usually in August.
  </p>

  <h2>An introduction to Croquet</h2>
  <p>
    Croquet is one of the very few games where men and women compete on level terms and across the generations from 15 to 90. Many games are played on a handicap basis but social games and some tournaments are played level.
  </p>
  <p>
    There are two different versions of croquet – Golf Croquet and Association Croquet. Most of our members play Golf Croquet but there is a small group of enthusiastic Association Croquet players which we would like to expand.
  </p>
  <p>
    Both versions of the game are played on the same lawn with the same equipment. Both can be played as singles or doubles.
  </p>
  <p>
    In Golf Croquet the players are all on the lawn at the same time and each side plays alternate strokes. The normal game is a 13-point game which means that the first side to win 7 hoops is the winner. Games can also be 7 or 19-point games. A 13-point game normally lasts from 30 – 60 minutes depending on how closely fought it is.
  </p>
  <p>
    Association Croquet is like snooker in that only one player is on the lawn at a time with the opponent(s) sitting watching. A full game is 26 points but 14 or 18-point games are quite common as a 26-point game can take 3 - 4 hours to play.
  </p>
  <p>
    Further information can be found about the two versions of the game from the Croquet Association’s website through the following links – <br />
    <%= link_to "www.croquet.org.uk/golf/", "www.croquet.org.uk/golf/" %> <br />
    <%= link_to "www.croquet.org.uk/association/", "www.croquet.org.uk/association/" %>
  </p>
</section>

app/views/main/join.html.erb
<section class="intro">
  <h1>Joining the Club</h1>
  <p>
    To join the Club you should contact the Secretary, Jean Cobbold, by e-mail <a href="mailto:cheamcroquetbowlsclub@gmail.com">
    cheamcroquetbowlsclub@gmail.com</a>
    or phone 0208642 0533. The Club’s year runs from 1st April. The annual subscription is £75. There is no joining fee.
  </p>
  <p>
    There is currently a waiting list for croquet membership but not for bowls membership.
  </p>
</section>

app/views/main/need.html.erb
<section class="intro">
  <h1>What you need to get started</h1>
  <p>
    The only requirement to start with is that you should wear flat-soled shoes in order to avoid damage to the lawn. When you join the Club and start to learn how to play the games you do not need to be involved in any expense as far as equipment is concerned. The Club provides mallets, ball and hoops for croquet and woods for bowls. Once you have decided that you like the game you will probably want to buy your own mallet for croquet or woods for bowls.
  </p>
  <p>
    When you start playing in matches and external tournaments you will need to get <q>whites</q> to play in as this is the accepted norm for matches and tournament play.
  </p>
</section>

app/views/main/newsletters.html.erb
<h1>Main#newsletters</h1>
<p>Find me in app/views/main/newsletters.html.erb</p>

app/views/main/programme.html.erb
<h1>Main#programme</h1>
<p>Find me in app/views/main/programme.html.erb</p>